/**
 * Originally GENERATED by a one-shot scrape of the legacy live course page.
 * Hand-maintained since the migration — edit it directly.
 *
 * Scraped from the rendered DOM rather than transcribed from
 * at-home-dog-boarding-course.php, because that file holds this copy in ~10
 * PHP arrays interpolated through heredoc helpers AND contains three malformed
 * HTML regions the browser silently repairs. The DOM is what visitors see.
 *
 * Treat as hand-maintained content from here on: edit this file directly.
 */

export const outline = [
  {
    "id": "day1",
    "title": "Day 1: Assessing Your Situation",
    "lessons": [
      {
        "title": "Lesson 1 - Introduction",
        "description": "Welcome to the course! This session will set the foundation for starting your dog-sitting business. Learn what to expect and how to build confidence in your ability to succeed."
      },
      {
        "title": "Lesson 2 - Assessing Your Situation",
        "description": "Analyze your home, time, family dynamics, and community resources to understand how they align with your dog-sitting goals."
      },
      {
        "title": "Lesson 3 - Market Research",
        "description": "Explore your local market to determine demand, competitive pricing, and the types of services offered. Then, learn how to stand out and provide value to your customers."
      },
      {
        "title": "Lesson 4 - Setting Realistic Goals",
        "description": "Define your ability to care for a number of dogs, your income expectations, and your personal priorities. Balance your business ambitions with your lifestyle and family needs."
      },
      {
        "title": "Lesson 5 - Creating a Dream Personal Plan",
        "description": "Combine all of this information into a personal plan that combines business goals, financial needs, and the life you want to create for yourself and your family."
      }
    ]
  },
  {
    "id": "day2",
    "title": "Day 2: Transforming Your Home",
    "lessons": [
      {
        "title": "Lesson 1 - Introduction",
        "description": "Discover how to prepare your home to create a safe, functional, and inviting environment for dogs and their owners."
      },
      {
        "title": "Lesson 2 - Entryway",
        "description": "Design a secure and welcoming entryway with double layers of separation, organized storage, and safety features like cameras and secure locks."
      },
      {
        "title": "Lesson 3 - Living Rooms",
        "description": "Learn how to dog-proof your living spaces while maintaining a clean and beautiful environment. This guide will also provide tips for minimalism, clutter control, and photo-ready spaces."
      },
      {
        "title": "Lesson 4 - Bedrooms",
        "description": "Set up cozy and clean sleeping areas for dogs, including protected linens, easy-to-clean surfaces, and plenty of comfortable dog beds."
      },
      {
        "title": "Lesson 5 - Feeding Station",
        "description": "Create an organized and hygienic feeding area with secure food storage, durable bowls, and attention to special dietary needs."
      },
      {
        "title": "Lesson 6 - Water Stations",
        "description": "Ensure access to clean and fresh water with multiple, easy-to-clean water stations that are safe and accessible."
      },
      {
        "title": "Lesson 7 - Outside Area",
        "description": "Transform your backyard into a dog-friendly oasis with secure fencing, shaded areas, cleanup stations, and space for play and exercise."
      },
      {
        "title": "Lesson 8 - Flooring",
        "description": "Master cleaning strategies for all surfaces in your home, using eco-friendly methods and tools to maintain a fresh and inviting space."
      },
      {
        "title": "Lesson 9 - Cleaning",
        "description": "Understand the impact of dogs on different flooring types and how to maintain, clean, and protect your home’s surfaces."
      }
    ]
  },
  {
    "id": "day3",
    "title": "Day 3: Business Planning and Launching",
    "lessons": [
      {
        "title": "Lesson 1 - Creating your Business Plan",
        "description": "Learn the core elements of a business plan, including budgeting, expenses, marketing strategies, and revenue forecasting."
      },
      {
        "title": "Lesson 2 - Financial plan and outlook",
        "description": "Learn how to craft a detailed business plan for your home-based dog-care business, covering market analysis, financial planning, and growth strategies to position yourself for success."
      },
      {
        "title": "Lesson 3 - Branding",
        "description": "Learn how to create a compelling brand for your dog boarding business that reflects your core values, attracts ideal clients, and sets the tone for an unforgettable experience for dogs and their owners."
      },
      {
        "title": "Lesson 4 - Launching on Different Platforms",
        "description": "Get step-by-step guidance on setting up accounts on platforms like Rover and other dog-sitting websites to increase visibility."
      },
      {
        "title": "Lesson 5 - Announcing on Social Media",
        "description": "Learn how to create engaging social media content, target your audience, and grow your presence on key platforms."
      },
      {
        "title": "Lesson 6 - Emailing Local Friends and Family",
        "description": "Write professional yet friendly emails to your personal network, letting them know about your new business and asking for referrals."
      }
    ]
  },
  {
    "id": "day4",
    "title": "Day 4: Setting Up Your Business",
    "lessons": [
      {
        "title": "Lesson 1 - Introduction",
        "description": "Learn the essential legal, financial, and operational steps to establish a successful home-based dog-sitting business, ensuring compliance, proper tax management, and a solid foundation for long-term success."
      },
      {
        "title": "Lesson 2 - Business Structure and Licensing",
        "description": "Learn to choose the right business structure, register your business, obtain necessary permits, and comply with local zoning and HOA regulations for a legal home-based dog-sitting business."
      },
      {
        "title": "Lesson 3 - Setting Up Payment Systems",
        "description": "Learn how to accept client payments securely and conveniently, whether through cash, checks, mobile payment apps, or dedicated invoicing software."
      },
      {
        "title": "Lesson 4 - Insurance, Liability, Contracts and Policies",
        "description": "Protect your business with insurance, clear client contracts, and strategic pricing to manage risks, build trust, and ensure steady income."
      },
      {
        "title": "Lesson 5 - Building Community Relationships",
        "description": "Foster positive relationships with neighbors by setting boundaries, managing noise, and addressing concerns to ensure smooth business operations within the community."
      },
      {
        "title": "Lesson 6 - Setting Up an Online Presence",
        "description": "Create a professional website and complete your Google Business setup to showcase services, build credibility, and attract local clients."
      }
    ]
  },
  {
    "id": "day5",
    "title": "Day 5: Client Relations and Communication",
    "lessons": [
      {
        "title": "Lesson 1 - Introduction",
        "description": "Learn how to streamline client onboarding, establish professional communication, leverage social media for engagement, and build strong, loyal client relationships through personalized care and consistent, thoughtful interaction."
      },
      {
        "title": "Lesson 2 - New Client Interest",
        "description": "Streamline new client interest with clear communication, policy discussions, and automated reminders to build trust and ensure a smooth start."
      },
      {
        "title": "Lesson 3 - Establishing Professional Communication",
        "description": "Build trust and credibility with clear, consistent messaging, prompt responses, and a professional yet friendly tone."
      },
      {
        "title": "Lesson 4 - Utilizing Social Media",
        "description": "Use platforms like Facebook, Instagram, and TikTok to showcase your services, share engaging content, and connect personally with potential clients."
      },
      {
        "title": "Lesson 5 - Building and Strengthening Client Relationships",
        "description": "Foster loyalty and referrals by forming genuine connections, providing personalized care, and maintaining thoughtful communication with clients."
      }
    ]
  },
  {
    "id": "day6",
    "title": "Day 6: Understanding Dog Behavior",
    "lessons": [
      {
        "title": "Lesson 1 - Introduction",
        "description": "Learn to assess temperament, manage group dynamics, use positive reinforcement, decode communication, and manage stress to create a supportive and safe environment for dogs."
      },
      {
        "title": "Lesson 2 - The Meet and Greet",
        "description": "Learn how to assess a dog’s temperament, energy level, and compatibility with other dogs and your home environment during an initial interaction. Understand the questions to ask and behaviors to observe."
      },
      {
        "title": "Lesson 3 - Assessing and Welcoming Dogs",
        "description": "Learn how to evaluate a dog’s temperament and energy during initial interactions, assess compatibility with other dogs, and identify appropriate engagement for varying energy levels."
      },
      {
        "title": "Lesson 4 - Managing Group Dynamics and Socialization",
        "description": "Master techniques for safe socialization, managing group play, preventing conflicts, and selecting appropriate toys that promote healthy behaviors and cooperation."
      },
      {
        "title": "Lesson 5 - Behavioral Guidance and Training",
        "description": "Focus on using positive reinforcement to correct undesirable behaviors, build trust, and manage separation anxiety, fostering a safe and supportive environment."
      },
      {
        "title": "Lesson 6 - Understanding Dog Communication and Stress",
        "description": "Decode dog body language to recognize emotional states, manage stress with calming techniques, control excessive barking, and identify early signs of illness or discomfort for proper care."
      }
    ]
  },
  {
    "id": "day7",
    "title": "Day 7: Emergency and Special Situations",
    "lessons": [
      {
        "title": "Lesson 1 - Introduction",
        "description": "Learn to manage dog behavior issues, handle emergencies like lost pets and medical crises, prepare for environmental challenges, and create backup plans for personal emergencies to ensure safety, communication, and business continuity."
      },
      {
        "title": "Lesson 2 - Handling Dog Behavior Issues",
        "description": "Learn safe intervention techniques for challenging behaviors, manage accidents and health issues, and use calming strategies to address separation anxiety while ensuring safety and clear communication with owners."
      },
      {
        "title": "Lesson 3 - Emergency Situations with Dogs",
        "description": "Develop strategies for preventing and managing emergencies, including lost pets, medical issues, and illness outbreaks, with first aid, quarantine procedures, and effective owner communication."
      },
      {
        "title": "Lesson 4 - Situational and Environmental Challenges",
        "description": "Prepare for emergencies with an evacuation plan, emergency kit, and communication strategies, while ensuring dog safety during crises and severe weather, and establishing protocols for unreachable owners."
      },
      {
        "title": "Lesson 5 - Personal Emergencies and Backup Plans",
        "description": "Prepare for personal emergencies by setting up backup caregivers, organizing dog care records, and maintaining a contact list and communication plan to ensure business continuity."
      }
    ]
  },
  {
    "id": "day8",
    "title": "Day 8: Scaling your Business",
    "lessons": [
      {
        "title": "Lesson 1 - Introduction",
        "description": "Learn to expand your business by adding new services, creating value-added packages, offering specialized care, and introducing supplementary revenue streams to enhance client satisfaction, trust, and loyalty while boosting revenue."
      },
      {
        "title": "Lesson 2 - Expanding Service Offerings",
        "description": "Grow your business by adding services like dog walking, grooming, training, and enrichment activities to meet diverse client needs, boost satisfaction, and create new revenue streams."
      },
      {
        "title": "Lesson 3 - Creating Value-Added Packages",
        "description": "Boost engagement and revenue by offering subscription services, hosting events, and forming partnerships with local businesses to create joint services and referral opportunities."
      },
      {
        "title": "Lesson 4 - Specialized and Premium Services",
        "description": "Enhance your business with specialized care for senior or special needs dogs, fitness programs, premium health coaching, and compassionate services like pet loss support to build trust and loyalty."
      },
      {
        "title": "Lesson 5 - Supplementary Revenue Streams",
        "description": "Grow your business by offering homemade dog meals, pet products, professional photography, and pet transportation services, providing added convenience and value for clients."
      }
    ]
  },
  {
    "id": "day9",
    "title": "Day 9: Financial Management",
    "lessons": [
      {
        "title": "Lesson 1 - Introduction",
        "description": "Learn to streamline finances with effective tools for tracking income, expenses, and client records, manage taxes and budgeting, plan for growth, and simplify operations with invoicing, payroll, and bookkeeping tools."
      },
      {
        "title": "Lesson 2 - Organizing Financial Foundations",
        "description": "Streamline finances with a booking tracker, detailed income and expense spreadsheets, and organized client and pet records for efficient operations and emergency preparedness"
      },
      {
        "title": "Lesson 3 - Tax Considerations",
        "description": "Learn how to manage taxes for a home-based business, including deductible expenses, quarterly payments, and maintaining accurate financial records to avoid surprises at tax time."
      },
      {
        "title": "Lesson 4 - Budgeting and Planning",
        "description": "Effectively manage finances by creating a budget, building an emergency fund, planning for growth, and preparing for the future with an exit strategy and proper recordkeeping."
      },
      {
        "title": "Lesson 5 - Financial Operations",
        "description": "Simplify financial management with invoicing, payment processing, bookkeeping tools like QuickBooks, and payroll basics to manage hiring and team expenses efficiently."
      }
    ]
  }
] as const;

export const faqs = [
  {
    "icon": "person",
    "question": "Who is this course designed for?",
    "answer": "This course is for people who want to stay home more and love dogs. Whether you're a stay-at-home parent, remote worker, retiree, or simply looking for a fulfilling way to earn income, this course is for you."
  },
  {
    "icon": "cart-fill",
    "question": "Do I need to have business experience to take this course?",
    "answer": "No, you don’t need any prior business experience. This course will guide you step-by-step through everything you need to know."
  },
  {
    "icon": "house-door-fill",
    "question": "Do I need to own my home to start a dog boarding business?",
    "answer": "No, but you’ll need permission from your landlord if you’re renting. If owning isn’t an option, you can still explore related opportunities like dog walking or in-home dog sitting for others."
  },
  {
    "icon": "clock-fill",
    "question": "How much time do I need to dedicate to running this type of business?",
    "answer": "A few hours a day are needed to play with, clean up after, and feed the dogs. Simply being present with them is essential but doesn’t require extra effort."
  },
  {
    "icon": "tag-fill",
    "question": "What upfront costs should I expect to get started?",
    "answer": "If you already own a dog, your upfront costs will likely be minimal—maybe a few additional gates, bowls, beds, or cleaning supplies."
  },
  {
    "icon": "book-fill",
    "question": "Will this course teach me how to handle dog behavior issues?",
    "answer": "The course will help you assess whether a dog is a good fit to avoid behavior issues. It also teaches how to set up your home to minimize potential problems, but it doesn’t cover correcting existing behavioral issues."
  },
  {
    "icon": "display-fill",
    "question": "Can I run this business if I have a full-time remote job?",
    "answer": "Yes, as long as you’re home and able to supervise and care for the dogs, this business is a great fit for remote workers."
  },
  {
    "icon": "currency-dollar",
    "question": "How quickly can I start making money after completing the course?",
    "answer": "You can start getting clients even before finishing the course. The early sections focus on setting up your home and attracting clients, so you can begin earning quickly."
  },
  {
    "icon": "tree-fill",
    "question": "What if I live in a rural area—can I still succeed?",
    "answer": "Yes! While attracting daycare clients might be more challenging, many people are willing to travel for the unique experience of having their dogs cared for in a spacious, natural setting."
  },
  {
    "icon": "person-walking",
    "question": "Will this course help me get clients?",
    "answer": "Absolutely. The course includes strategies and templates to help you effectively advertise and attract clients."
  },
  {
    "icon": "tools",
    "question": "What tools or resources are included in the course?",
    "answer": "You’ll get business plan templates, income and expense tracking sheets, advertising templates, and more resources as the course grows."
  },
  {
    "icon": "receipt",
    "question": "Do I need any certifications or licenses to start a dog boarding business?",
    "answer": "Depending on your location, you may need a business permit. Be sure to check your local requirements."
  },
  {
    "icon": "airplane-fill",
    "question": "What happens if I need to take a break or go on vacation?",
    "answer": "You can pause your business at any time or find someone to cover for you while you’re away."
  },
  {
    "icon": "wifi",
    "question": "How is this course delivered?",
    "answer": "The course is delivered through pre-recorded video lessons, so you can learn at your own pace."
  },
  {
    "icon": "person",
    "question": "What kind of support will I have during and after the course?",
    "answer": "You’ll have access to a supportive community where you can ask questions and connect with me directly."
  },
  {
    "icon": "coin",
    "question": "Is there a money-back guarantee if I’m not satisfied?",
    "answer": "Yes, we offer a money-back guarantee if you’re not happy with the course."
  }
] as const;

export const disclaimers = [
  {
    "title": "Legal and Financial Disclaimer",
    "body": "This course does not guarantee financial success or specific income levels. While the course provides strategies to help you attract clients, the amount of money you earn will depend on various factors, including your location, your home setup, and your prior experience. Results may vary based on individual effort and circumstances. Starting a dog boarding business involves inherent risks, as dogs are animals and cannot be fully controlled. The course will set you up for success, but it is your responsibility to avoid situations that could put you or the dogs in your care at risk."
  },
  {
    "title": "Licensing and Legal Requirements",
    "body": "Participants are solely responsible for ensuring they comply with all local laws, permits, and regulations required to operate a dog boarding business in their area. While the course provides general guidance on city and county permitting, as well as information on filing taxes and setting up your business, it does not constitute legal advice. It is up to you to ensure all necessary legal and regulatory requirements are met."
  },
  {
    "title": "Health and Safety Disclaimer",
    "body": "You are fully responsible for ensuring the safety of your home and the dogs in your care. While the course offers guidance on assessing dog behavior and creating a safe environment, the final decisions and responsibilities lie with you."
  },
  {
    "title": "Intellectual Property",
    "body": "All course content, including templates, resources, and videos, is for personal use only. Redistribution, resale, or unauthorized sharing of the materials is strictly prohibited."
  },
  {
    "title": "Course Limitations",
    "body": "This course covers the basics of starting and running a dog boarding business but does not include advanced training in dog behavior, medical care, or other specialized areas. If you wish to pursue further certifications, additional training may be required. All advice provided is based on personal experience and does not constitute professional certification in animal behavior or care."
  },
  {
    "title": "Refund Policy",
    "body": "We stand behind the value of this course. However, if you are unable to secure clients or determine that this business is not the right fit for you, we offer a money-back guarantee. Specific details of the refund policy will be outlined at the time of purchase."
  }
] as const;

export const audience = {
  "whoFor": [
    "Perfect for dog lovers wanting to earn money from home.",
    "Suitable for stay-at-home parents, remote workers, or retirees.",
    "Learn to turn your passion for dogs into a business.",
    "Tips for creating a safe, dog-friendly home.",
    "Strategies for attracting clients and managing dogs.",
    "Solutions for handling dog fights and cleaning efficiently.",
    "Make dog care enjoyable, stress-free, and profitable."
  ],
  "whoNotFor": [
    "This course requires prior dog care experience.",
    "Dog behavior and needs are essential but not detailed here.",
    "Success requires strong commitment to being present with the dogs.",
    "A support system is needed for managing the business during absences.",
    "Comfort with cleaning and handling behavioral challenges is necessary.",
    "Setting up a space and leaving dogs alone won’t work.",
    "This course will help you succeed in dog care’s joys and challenges."
  ]
} as const;

export const learn = [
  {
    "title": "Setting Up for Success",
    "bullets": [
      "Learn how to evaluate your space, resources, and legal steps for starting a dog boarding business.",
      "Create a safe, welcoming environment for dogs while maintaining your home's comfort.",
      "Access worksheets, sample spreadsheets, and contracts to help plan and organize your business."
    ]
  },
  {
    "title": "Running and Growing Your Business",
    "bullets": [
      "Develop a business plan, branding strategies, and methods for attracting clients.",
      "Master client relations and ensure a peaceful environment for dogs in your care.",
      "Utilize customizable flyers, contracts, and tools to streamline business operations and scaling."
    ]
  },
  {
    "title": "Handling Challenges and Special Situations",
    "bullets": [
      "Gain insights into dog behavior and how to manage emergencies and special care situations.",
      "Learn techniques to maintain safety and wellbeing for dogs in your care.",
      "Access practical templates and protocols to handle special situations with confidence."
    ]
  }
] as const;

export const testimonials = [
  {
    "avatar": "/images/course/testimonial_leila.jpg",
    "quote": "Selena knows her stuff! With over a decade of experience in the business and a lifetime of loving dogs, she offers the tools you'll need to start a successful dog business. I’ve been working with her for over a year since before I got my first guest, to now where I have dozens of repeat clients. I'm grateful for her mentorship and highly recommend her course!",
    "name": "Leila Gates",
    "role": "Teacher"
  },
  {
    "avatar": "/images/course/testimonial_sara.jpg",
    "quote": "Honestly, I thought that doing the dog business would not require much knowledge, it could be intuitive, but when I started receiving information from Selena, I realized that I needed valuable information that only she had because of her experience. I felt taken by the hand and when we received the first dog",
    "more": "(only 5 days after starting the course) everything made so much sense, when you do it, the experience that she has, becomes very evident, and you feel with the ability to solve the small challenges. Today I feel very happy, I have the size of a business that fits my family and that pays the rent.",
    "name": "Sara Botero",
    "role": "UX Designer"
  },
  {
    "avatar": "/images/course/testimonial_cuau.jpg",
    "quote": "Selena’s “Hound Away From Home” course is a well organized training that has been instrumental in launching our own dog business. Selena's knowledge, guidance, and well-structured lessons are detailed and practical, covering everything from dog care to business management and setting achievable goals.",
    "more": "Her passion, love for dogs and experience shine through, making the learning engaging. From explaining how to set up a welcoming entryway for furry guests to offering practical tips for creating a safe and fun backyard, the course is comprehensive. The summaries, checklists, and worksheets are ready to be applied to all the activities involved in this business. Highly recommended for anyone serious about launching a successful home dog boarding business – a must-have investment!",
    "name": "Cuau Leyva",
    "role": "Software Engineer"
  }
] as const;

export const infoboxes = [
  {
    "image": "twentyfourhours",
    "text": "Escape the 9-to-5 grind and enjoy flexibility."
  },
  {
    "image": "boss",
    "text": "Be your own boss while caring for adorable pups."
  },
  {
    "image": "parents",
    "text": "Ideal for parents or aspiring entrepreneurs."
  },
  {
    "image": "reward",
    "text": "Earn with a rewarding business."
  },
  {
    "image": "caring",
    "text": "Find fulfillment caring for dogs."
  }
] as const;

export const coach = [
  "Hi, I’m Selena Trotter, and I’ve been running a successful at-home dog boarding business since 2012. It all started one summer during a break from my high school teaching career when I began looking after dogs. What began as a side hustle quickly became a fulfilling, full-time business that allowed me to stay home -all while earning a great income. Since then, I’ve cared for over 1,000 dogs, creating a safe, loving, and happy environment.",
  "Running this business has given me the freedom to raise my kids at home and involve them in the work, teaching them responsibility and the value of caring for others. Over the years, I’ve learned the ins and outs of managing a successful dog boarding business, from handling unique challenges to enjoying the incredible rewards.",
  "With my background in teaching and executive coaching, I bring a wealth of experience in guiding others to success. My practical, supportive approach is designed to help you achieve financial independence, time flexibility, and a deep sense of fulfillment. Whether you’re looking to supplement your income or create a full-time career, I’m here to share everything to help you get started, avoid pitfalls, and find joy in building a business centered around the love of dogs."
] as const;
